/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

/** Deprecated compatibility layer. New code must include `BKE_object_transform_clarity.hh`. */

#include "BKE_object_transform_clarity.hh"

namespace blender {

using MayaObjectTransform = ClarityObjectTransform;
using eMayaRotationOrder = eClarityRotationOrder;
using MayaTransformCapabilities = ClarityTransformCapabilities;
using eMayaTransformSetPolicy = eClarityTransformSetPolicy;
using MayaTransformSetOptions = ClarityTransformSetOptions;
using MayaLinearDecomposition = ClarityLinearDecomposition;

}  // namespace blender

#define MAYA_ROT_ORDER_XYZ CLARITY_ROT_ORDER_XYZ
#define MAYA_ROT_ORDER_YZX CLARITY_ROT_ORDER_YZX
#define MAYA_ROT_ORDER_ZXY CLARITY_ROT_ORDER_ZXY
#define MAYA_ROT_ORDER_XZY CLARITY_ROT_ORDER_XZY
#define MAYA_ROT_ORDER_YXZ CLARITY_ROT_ORDER_YXZ
#define MAYA_ROT_ORDER_ZYX CLARITY_ROT_ORDER_ZYX

#define MAYA_TRANSFORM_SET_CHANNELS CLARITY_TRANSFORM_SET_CHANNELS
#define MAYA_TRANSFORM_SET_TRANSLATION_ONLY CLARITY_TRANSFORM_SET_TRANSLATION_ONLY
#define MAYA_TRANSFORM_SET_ROTATION_ONLY CLARITY_TRANSFORM_SET_ROTATION_ONLY
#define MAYA_TRANSFORM_SET_SCALE_ONLY CLARITY_TRANSFORM_SET_SCALE_ONLY
#define MAYA_TRANSFORM_SET_RESET_PIVOTS CLARITY_TRANSFORM_SET_RESET_PIVOTS
#define MAYA_TRANSFORM_SET_BAKE_SPECIAL_CHANNELS CLARITY_TRANSFORM_SET_BAKE_SPECIAL_CHANNELS

#define BKE_maya_decompose_linear_compatible BKE_clarity_decompose_linear_compatible
#define BKE_maya_matrix_orthonormalize BKE_clarity_matrix_orthonormalize
#define BKE_maya_rotate_axis_quaternion BKE_clarity_rotate_axis_quaternion
#define BKE_maya_rotate_pivot_world_get BKE_clarity_rotate_pivot_world_get
#define BKE_maya_rotation_order_from_blender BKE_clarity_rotation_order_from_blender
#define BKE_maya_rotation_order_to_blender BKE_clarity_rotation_order_to_blender
#define BKE_maya_scale_pivot_world_get BKE_clarity_scale_pivot_world_get
#define BKE_maya_transform_capabilities_get BKE_clarity_transform_capabilities_get
#define BKE_maya_transform_channel_matrix BKE_clarity_transform_channel_matrix
#define BKE_maya_transform_dag_local_matrix BKE_clarity_transform_dag_local_matrix
#define BKE_maya_transform_rotation_matrix BKE_clarity_transform_rotation_matrix
#define BKE_maya_transform_set_channel_matrix BKE_clarity_transform_set_channel_matrix
#define BKE_maya_transform_set_defaults BKE_clarity_transform_set_defaults
#define BKE_maya_transform_set_rotate_axis BKE_clarity_transform_set_rotate_axis
#define BKE_maya_transform_set_rotate_pivot BKE_clarity_transform_set_rotate_pivot
#define BKE_maya_transform_set_rotation_matrix BKE_clarity_transform_set_rotation_matrix
#define BKE_maya_transform_set_rotation_order BKE_clarity_transform_set_rotation_order
#define BKE_maya_transform_set_scale_pivot BKE_clarity_transform_set_scale_pivot
#define BKE_maya_transform_world_matrix BKE_clarity_transform_world_matrix

#define BKE_object_uses_maya_transform BKE_object_uses_clarity_transform
#define BKE_object_maya_transform_ensure BKE_object_clarity_transform_ensure
#define BKE_object_maya_transform_reset BKE_object_clarity_transform_reset
#define BKE_object_maya_set_dag_local_matrix BKE_object_clarity_set_dag_local_matrix
#define BKE_object_maya_set_world_matrix BKE_object_clarity_set_world_matrix
#define BKE_object_maya_rotate_pivot_world_get BKE_object_clarity_rotate_pivot_world_get
#define BKE_object_maya_scale_pivot_world_get BKE_object_clarity_scale_pivot_world_get
#define BKE_object_maya_rotate_pivot_world_set BKE_object_clarity_rotate_pivot_world_set
#define BKE_object_maya_scale_pivot_world_set BKE_object_clarity_scale_pivot_world_set
#define BKE_object_maya_local_axis_world_get BKE_object_clarity_local_axis_world_get
#define BKE_object_maya_parent_axis_world_get BKE_object_clarity_parent_axis_world_get
#define BKE_object_maya_gimbal_axis_world_get BKE_object_clarity_gimbal_axis_world_get
#define BKE_object_maya_parent_keep_transform BKE_object_clarity_parent_keep_transform
#define BKE_object_maya_clear_parent_keep_transform BKE_object_clarity_clear_parent_keep_transform
