/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

/** Deprecated compatibility layer. New code must include `BKE_clarity_constraints.hh`. */

#include "BKE_clarity_constraints.hh"

namespace blender {

using MayaConstraint = ClarityConstraint;
using MayaConstraintTarget = ClarityConstraintTarget;
using MayaAimConstraintSettings = ClarityAimConstraintSettings;
using eMayaConstraintType = eClarityConstraintType;
using eMayaWorldUpType = eClarityWorldUpType;
using eMayaTransformChannel = eClarityTransformChannel;

}  // namespace blender

#define MAYA_CONSTRAINT_POINT CLARITY_CONSTRAINT_POINT
#define MAYA_CONSTRAINT_ORIENT CLARITY_CONSTRAINT_ORIENT
#define MAYA_CONSTRAINT_SCALE CLARITY_CONSTRAINT_SCALE
#define MAYA_CONSTRAINT_PARENT CLARITY_CONSTRAINT_PARENT
#define MAYA_CONSTRAINT_AIM CLARITY_CONSTRAINT_AIM

#define MAYA_WORLD_UP_SCENE CLARITY_WORLD_UP_SCENE
#define MAYA_WORLD_UP_OBJECT CLARITY_WORLD_UP_OBJECT
#define MAYA_WORLD_UP_OBJECT_ROTATION CLARITY_WORLD_UP_OBJECT_ROTATION
#define MAYA_WORLD_UP_VECTOR CLARITY_WORLD_UP_VECTOR
#define MAYA_WORLD_UP_NONE CLARITY_WORLD_UP_NONE

#define MAYA_TRANSFORM_CHANNEL_TRANSLATION CLARITY_TRANSFORM_CHANNEL_TRANSLATION
#define MAYA_TRANSFORM_CHANNEL_ROTATION CLARITY_TRANSFORM_CHANNEL_ROTATION
#define MAYA_TRANSFORM_CHANNEL_SCALE CLARITY_TRANSFORM_CHANNEL_SCALE

#define BKE_maya_constraint_add BKE_clarity_constraint_add
#define BKE_maya_constraint_maintain_offset_set BKE_clarity_constraint_maintain_offset_set
#define BKE_maya_constraint_output_apply BKE_clarity_constraint_output_apply
#define BKE_maya_constraint_remove BKE_clarity_constraint_remove
#define BKE_maya_constraint_target_add BKE_clarity_constraint_target_add
#define BKE_maya_constraint_target_pivot_world_get \
  BKE_clarity_constraint_target_pivot_world_get
#define BKE_maya_constraints_clear BKE_clarity_constraints_clear
#define BKE_maya_point_constraint_evaluate BKE_clarity_point_constraint_evaluate

#define BKE_object_eval_maya_channels_init BKE_object_eval_clarity_channels_init
#define BKE_object_eval_maya_local_transform BKE_object_eval_clarity_local_transform
#define BKE_object_maya_evaluated_channels_invalidate \
  BKE_object_clarity_evaluated_channels_invalidate
#define BKE_object_maya_channel_is_driven BKE_object_clarity_channel_is_driven
