/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

/** Deprecated compatibility layer. New code must include `ED_clarity.hh`. */

#include "ED_clarity.hh"

namespace blender::ed::maya {

using namespace clarity;

using MayaDispatchResult = clarity::ClarityDispatchResult;
using MayaPivotEditTarget = clarity::ClarityPivotEditTarget;
using MayaPivotTargetType = clarity::ClarityPivotTargetType;
using MayaPivotUsage = clarity::ClarityPivotUsage;
using eMayaPivotResetMode = clarity::eClarityPivotResetMode;
using eMayaPivotBakeMode = clarity::eClarityPivotBakeMode;
using MayaPivotFrame = clarity::ClarityPivotFrame;
using MayaPivotSnapTargetType = clarity::ClarityPivotSnapTargetType;
using MayaPivotSnapResult = clarity::ClarityPivotSnapResult;
using MayaPivotToolSettings = clarity::ClarityPivotToolSettings;
using MayaObjectRuntimeRef = clarity::ClarityObjectRuntimeRef;
using MayaPivotEditTargetBackend = clarity::ClarityPivotEditTargetBackend;
using MayaSnapMode = clarity::ClaritySnapMode;
using MayaTransformConstraint = clarity::ClarityTransformConstraint;
using eMayaStepSnapMode = clarity::eClarityStepSnapMode;
using MayaStepSnapSettings = clarity::ClarityStepSnapSettings;
using MayaSnapToleranceSettings = clarity::ClaritySnapToleranceSettings;
using MayaNavigationDebugStage = clarity::ClarityNavigationDebugStage;

}  // namespace blender::ed::maya

namespace blender {

void ED_operatortypes_maya();

}  // namespace blender

#define MAYA_PIVOT_RESET_CENTER CLARITY_PIVOT_RESET_CENTER
#define MAYA_PIVOT_RESET_ZERO CLARITY_PIVOT_RESET_ZERO
#define MAYA_PIVOT_BAKE_POSITION CLARITY_PIVOT_BAKE_POSITION
#define MAYA_PIVOT_BAKE_ORIENTATION CLARITY_PIVOT_BAKE_ORIENTATION
#define MAYA_PIVOT_BAKE_BOTH CLARITY_PIVOT_BAKE_BOTH
#define MAYA_STEP_SNAP_RELATIVE CLARITY_STEP_SNAP_RELATIVE
#define MAYA_STEP_SNAP_ABSOLUTE CLARITY_STEP_SNAP_ABSOLUTE

#define ED_maya_event_dispatch ED_clarity_event_dispatch
#define ED_maya_gizmo_trace_enabled ED_clarity_gizmo_trace_enabled
#define ED_maya_interaction_enabled ED_clarity_interaction_enabled
#define ED_maya_interaction_frame_rate_limit ED_clarity_interaction_frame_rate_limit
#define ED_maya_interaction_preset_enabled ED_clarity_interaction_preset_enabled
#define ED_maya_move_keep_spacing_get ED_clarity_move_keep_spacing_get
#define ED_maya_navigation_debug_active ED_clarity_navigation_debug_active
#define ED_maya_navigation_debug_stage_sample ED_clarity_navigation_debug_stage_sample
#define ED_maya_object_runtime_ref_create ED_clarity_object_runtime_ref_create
#define ED_maya_object_runtime_ref_resolve ED_clarity_object_runtime_ref_resolve
#define ED_maya_pivot_active_axis_set ED_clarity_pivot_active_axis_set
#define ED_maya_pivot_bake ED_clarity_pivot_bake
#define ED_maya_pivot_custom_matrix_get ED_clarity_pivot_custom_matrix_get
#define ED_maya_pivot_custom_orientation_get ED_clarity_pivot_custom_orientation_get
#define ED_maya_pivot_edit_data_get ED_clarity_pivot_edit_data_get
#define ED_maya_pivot_edit_target_create ED_clarity_pivot_edit_target_create
#define ED_maya_pivot_edit_target_get ED_clarity_pivot_edit_target_get
#define ED_maya_pivot_event_pre_modal ED_clarity_pivot_event_pre_modal
#define ED_maya_pivot_manipulator_state_get ED_clarity_pivot_manipulator_state_get
#define ED_maya_pivot_orientation_aim ED_clarity_pivot_orientation_aim
#define ED_maya_pivot_reset_all ED_clarity_pivot_reset_all
#define ED_maya_pivot_reset_orientation ED_clarity_pivot_reset_orientation
#define ED_maya_pivot_reset_position ED_clarity_pivot_reset_position
#define ED_maya_pivot_snap_preview_get ED_clarity_pivot_snap_preview_get
#define ED_maya_pivot_tool_settings_get ED_clarity_pivot_tool_settings_get
#define ED_maya_pivot_tool_settings_set ED_clarity_pivot_tool_settings_set
#define ED_maya_pivot_undo_begin ED_clarity_pivot_undo_begin
#define ED_maya_runtime_free ED_clarity_runtime_free
#define ED_maya_shift_transform_prepare ED_clarity_shift_transform_prepare
#define ED_maya_snap_key_event_apply ED_clarity_snap_key_event_apply
#define ED_maya_snap_mode_get ED_clarity_snap_mode_get
#define ED_maya_snap_mode_set ED_clarity_snap_mode_set
#define ED_maya_snap_override_get ED_clarity_snap_override_get
#define ED_maya_snap_override_release_all ED_clarity_snap_override_release_all
#define ED_maya_snap_step_settings_get ED_clarity_snap_step_settings_get
#define ED_maya_snap_tolerance_px_get ED_clarity_snap_tolerance_px_get
#define ED_maya_snap_tolerance_settings_get ED_clarity_snap_tolerance_settings_get
#define ED_maya_transform_begin ED_clarity_transform_begin
#define ED_maya_transform_constraint_get ED_clarity_transform_constraint_get
#define ED_maya_transform_end ED_clarity_transform_end
#define ED_maya_transform_slide_invoke ED_clarity_transform_slide_invoke
#define ED_maya_transform_update ED_clarity_transform_update
#define ED_maya_undo_step_clear ED_clarity_undo_step_clear
#define ED_maya_undo_step_store ED_clarity_undo_step_store
#define ED_maya_undo_steps_restore ED_clarity_undo_steps_restore
#define ED_maya_viewport_debug_event ED_clarity_viewport_debug_event
